ScrollReveal({distance: "40px", delay: 300});
ScrollReveal().reveal(".first-p", {delay: 1000});
ScrollReveal().reveal(".first-b", {delay: 1000});
ScrollReveal().reveal(".first-sub-container", {delay: 800})
ScrollReveal().reveal(".first-sub-c1", {delay: 1300})
ScrollReveal().reveal(".second-div")
ScrollReveal().reveal(".third-p")
ScrollReveal().reveal(".third-div")
ScrollReveal().reveal(".fourth-div")
ScrollReveal().reveal(".fourth-sub-div1")
ScrollReveal().reveal(".fourth-sub-div2")
ScrollReveal().reveal(".fourth-sub-div3")
ScrollReveal().reveal(".fourth-sub-div4")
ScrollReveal().reveal(".fourth-sub-div5")
ScrollReveal().reveal(".fourth-sub-div6")
ScrollReveal().reveal(".fifth-p1")
ScrollReveal().reveal(".fifth-p2", {delay: 350})
ScrollReveal().reveal(".fifth-p3", {delay: 400})
ScrollReveal().reveal(".fifth-div", {delay: 450})
ScrollReveal().reveal(".sixth-p1")
ScrollReveal().reveal(".sixth-p2", {delay: 350})
ScrollReveal().reveal(".sixth-p3", {delay: 400})
ScrollReveal().reveal(".sixth-div", {delay: 450})
ScrollReveal().reveal(".seventh-p1")
ScrollReveal().reveal(".seventh-p2", {delay: 350})
ScrollReveal().reveal(".seventh-p3", {delay: 400})
ScrollReveal().reveal(".seventh-div", {delay: 450})
ScrollReveal().reveal(".eigth-div")
ScrollReveal().reveal(".eigth-h1", {delay: 400})
ScrollReveal().reveal(".eigth-a", {delay: 400})
